Homework_2

Estructura de la funcion
Argumentos = (par1, par2, ...)

nombre_de_funcion <- function(par1, par2, ...) {
  cuerpo
  cuerpo
  cuerpo
  cuerpo
  return(resultado)
}

```{r}
#Ejemplo funcion

suma_multi <- function(x, y) {
  resultado <- x + y
  resultado2 <- x * y
  r <- list(resultado, resultado2)
  return(r)
}

suma_multi(x=25, y=4)

```
Argumentos de una funcion

```{r}
f <- function() {
  c("Hola Mundo")
}

f()

```
Argumentos de una funcion #2

```{r}
mi_funcion <- function(arg1, arg2) {
# Cuerpo de la función
  # realizar cualquier operación utilizando los argumentos
  resultado <- arg1 + arg2
  return(resultado)
}

# Llamar a la función con argumentos
resultado_final <- mi_funcion(3, 4)
print(resultado_final)

```

Argumentos por valor
```{r}

area_rectangulo <- function(lado1, lado2) # (lado1, lado2)
{
  area <- lado1 * lado2
  print(paste("el área del rectangulo es ", area))
}

area_rectangulo(lado1 = 2, lado2 = 3)

class(area_rectangulo)

```
uso de lapply con funciones ejemplo

```{r}
# Definir una lista
mi_lista <- list(1, 2, 3, 4, 5)

# Definir una función que eleva al cuadrado un número
elevar_al_cuadrado <- function(x) {
  return(x^2)
}

# Aplicar la función a cada elemento de la lista usando lapply
resultado <- lapply(mi_lista, elevar_al_cuadrado)
print(resultado)

```

uso de sapply con funciones ejemplo

```{r}
# Definir una lista
mi_lista <- list(1, 2, 3, 4, 5)

# Definir una función que eleva al cuadrado un número
elevar_al_cuadrado <- function(x) {
  return(x^2)
}

# Aplicar la función a cada elemento de la lista usando sapply
resultado <- sapply(mi_lista, elevar_al_cuadrado)
print(resultado)


```
uso de vapply con funciones ejemplo
```{r}
# Definir un vector
mi_vector <- c(1, 2, 3, 4, 5)

# Definir una función que eleva al cuadrado un número
elevar_al_cuadrado <- function(x) {
  return(x^2)
}

# Aplicar la función al vector usando vapply
resultado <- vapply(mi_vector, elevar_al_cuadrado, numeric(1))
print(resultado)

```

